DROP TABLE IF EXISTS organizations CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TYPE IF EXISTS organization_type CASCADE;


CREATE TYPE organization_type AS ENUM (
    'TRUST',
    'PRIVATE_LIMITED_COMPANY',
    'OPEN_JOINT_STOCK_COMPANY'
);


CREATE TABLE users (
id SERIAL PRIMARY KEY,
login VARCHAR(50) UNIQUE NOT NULL,
password_hash VARCHAR(100) NOT NULL,
salt TEXT NOT NULL,
created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE organizations (
id SERIAL PRIMARY KEY,
name VARCHAR(200) NOT NULL,
coordinates_x DOUBLE PRECISION,
coordinates_y BIGINT,
annual_turnover FLOAT CHECK (annual_turnover >= 0),
type organization_type NOT NULL,
owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
street TEXT,
zip_code VARCHAR(20)
);
